apiVersion: v1
kind: Secret
metadata:
  name: miniocreds
  namespace: kubeflow
  annotations:
     serving.kserve.io/s3-endpoint: minio-api.mlflow:9000
     serving.kserve.io/s3-usehttps: "0"
     serving.kserve.io/s3-region: "us-east-1"
     serving.kserve.io/s3-useanoncredential: "false"
type: Opaque
data:
  AWS_ACCESS_KEY_ID: YWRtaW4= # replace with your base64 encoded minio user
  AWS_SECRET_ACCESS_KEY: dklSdFVhTE1pbkRzQWRtSU4= # replace with your base64 encoded minio secret key
  AWS_DEFAULT_REGION: dXMtZWFzdC0x # us-east-1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlflow-sa
  namespace: kubeflow
secrets:
  - name: miniocreds