{
 "title": "Iris Training - Virtual Minds",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Weekly Average Accuracy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "mlflowdb",
     "rawSql": "SELECT\n  $__timeGroupAlias(m.timestamp, '1w'), AVG(m.value) AS \"WeeklyAccuracyAverage\"  FROM \n  (select r.run_uuid, e.experiment_id, m.key, m.value, FROM_UNIXTIME(m.timestamp/1000) as timestamp FROM experiments as e INNER JOIN runs as r ON r.experiment_id = e.experiment_id INNER JOIN metrics as m ON r.run_uuid = m.run_uuid where e.name = 'iris-experiment') m\nWHERE $__timeFilter(m.timestamp) GROUP BY 1 ORDER BY 1;                                       \n"
    }
   ]
  },
  {
   "title": "Daily Average Accuracy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "mlflowdb",
     "rawSql": "SELECT\n  $__timeGroupAlias(m.timestamp, '1d'), AVG(m.value) AS \"DailyAccuracyAverage\"  FROM \n  (select r.run_uuid, e.experiment_id, m.key, m.value, FROM_UNIXTIME(m.timestamp/1000) as timestamp FROM experiments as e INNER JOIN runs as r ON r.experiment_id = e.experiment_id INNER JOIN metrics as m ON r.run_uuid = m.run_uuid where e.name = 'iris-experiment') m\nWHERE $__timeFilter(m.timestamp) GROUP BY 1 ORDER BY 1;                                       \n\n\n"
    }
   ]
  },
  {
   "title": "Hourly Accuracy Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "mlflowdb",
     "rawSql": "SELECT\n  $__timeGroupAlias(m.timestamp, '1h'), AVG(m.value) AS \"HourlyAccuracyAverage\"  FROM \n  (select r.run_uuid, e.experiment_id, m.key, m.value, FROM_UNIXTIME(m.timestamp/1000) as timestamp FROM experiments as e INNER JOIN runs as r ON r.experiment_id = e.experiment_id INNER JOIN metrics as m ON r.run_uuid = m.run_uuid where e.name = 'iris-experiment') m\nWHERE $__timeFilter(m.timestamp) GROUP BY 1 ORDER BY 1;                                       \n\n"
    }
   ]
  }
 ]
}