apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    app: minio
spec:
  selector:
    matchLabels:
      app: minio
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 8
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: minio
      annotations: 
        app_version: "v1.0"
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        args: ["server", "/data", "--console-address", ":9001", "--address", ":9000"]
        env: 
          - name: MINIO_ROOT_USER
            valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: user
          - name: MINIO_ROOT_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: secretkey
        volumeMounts:
        - mountPath: /data
          name: minio-pvc 
      volumes:
      - name: minio-pvc
        persistentVolumeClaim:
          claimName: minio-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: minio-api
  labels:
    app: minio
spec:
  selector:
    app: minio
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: minio-ui
  labels:
    app: minio
spec:
  selector:
    app: minio
  ports:
    - port: 9001
      protocol: TCP
      targetPort: 9001