apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  database: bWxmbG93ZGI= # Base64 encoded "mlflowdb"
  username: YWRtaW4= # Base64 encoded "admin" 
  password: dklSdFVhTE1pbkRz # Base64 encoded "vIRtUaLMinDs"
  rootpassword: dklSdFVhTE1pbkRzQWRtSU4= # Base64 encoded "vIRtUaLMinDsAdmIN"
---

apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
type: Opaque
data:
  user: YWRtaW4=  # Base64 encoded "admin"
  secretkey: dklSdFVhTE1pbkRzQWRtSU4=  # Base64 encoded "vIRtUaLMinDsAdmIN"